-- =====================================================
-- MIGRATION: PRODUTOS VARIAÇÕES DE COR E ESTOQUE POR COR
-- =====================================================

begin;

-- 1. TABELA DE VARIAÇÕES DE PRODUTO
create table if not exists public.produto_variacoes (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.produtos(id) on delete cascade,
  cor_nome text not null,
  cor_hex text not null default '#234B36',
  fotos jsonb not null default '[]'::jsonb,
  ativo boolean not null default true,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists produto_variacoes_produto_id_idx
  on public.produto_variacoes (produto_id);

-- 2. EVOLUÇÃO DE PRODUTO_TAMANHOS COM VARIACAO_ID E COR
alter table public.produto_tamanhos
  add column if not exists variacao_id bigint references public.produto_variacoes(id) on delete cascade,
  add column if not exists cor text default 'Única',
  add column if not exists cor_hex text default '#234B36';

create index if not exists produto_tamanhos_variacao_id_idx
  on public.produto_tamanhos (variacao_id);

-- 3. EVOLUÇÃO DE PEDIDO_ITENS, RESERVAS_ESTOQUE E CONSIGNAÇÃO
alter table public.pedido_itens
  add column if not exists cor text,
  add column if not exists cor_hex text,
  add column if not exists variacao_id bigint;

alter table public.reservas_estoque
  add column if not exists cor text,
  add column if not exists variacao_id bigint;

alter table public.revenda_remessa_itens
  add column if not exists cor text,
  add column if not exists cor_hex text,
  add column if not exists variacao_id bigint;

alter table public.revenda_vendas
  add column if not exists cor text,
  add column if not exists cor_hex text,
  add column if not exists variacao_id bigint;

alter table public.revenda_devolucoes
  add column if not exists cor text,
  add column if not exists cor_hex text,
  add column if not exists variacao_id bigint;

-- 4. MIGRAÇÃO SEGURA DOS PRODUTOS EXISTENTES
-- Criar uma variação padrão para cada produto que ainda não possui variação
insert into public.produto_variacoes (produto_id, cor_nome, cor_hex, fotos, ordem, ativo)
select
  p.id,
  coalesce(nullif(trim(p.cor), ''), 'Única') as cor_nome,
  '#234B36' as cor_hex,
  coalesce(
    (
      select jsonb_agg(jsonb_build_object('foto', pf.foto, 'ordem', pf.ordem) order by pf.ordem)
      from public.produto_fotos pf
      where pf.produto_id = p.id
    ),
    case when p.foto is not null then jsonb_build_array(jsonb_build_object('foto', p.foto, 'ordem', 0)) else '[]'::jsonb end
  ) as fotos,
  0 as ordem,
  coalesce(p.ativo, true) as ativo
from public.produtos p
where not exists (
  select 1 from public.produto_variacoes pv where pv.produto_id = p.id
);

-- Vincular os registros existentes de produto_tamanhos à variação padrão correspondente
update public.produto_tamanhos pt
set
  variacao_id = pv.id,
  cor = pv.cor_nome,
  cor_hex = pv.cor_hex
from public.produto_variacoes pv
where pt.produto_id = pv.produto_id
  and pt.variacao_id is null;

-- 5. POLICIES E PERMISSÕES
alter table public.produto_variacoes enable row level security;

drop policy if exists produto_variacoes_public_select on public.produto_variacoes;
create policy produto_variacoes_public_select
on public.produto_variacoes
for select
using (true);

drop policy if exists produto_variacoes_admin_all on public.produto_variacoes;
create policy produto_variacoes_admin_all
on public.produto_variacoes
for all
to authenticated, service_role
using (true)
with check (true);

grant select on public.produto_variacoes to anon;
grant select, insert, update, delete on public.produto_variacoes to authenticated, service_role;
grant usage, select on sequence public.produto_variacoes_id_seq to authenticated, service_role;

commit;
