begin;

create table if not exists public.checkout_rate_limits (
  id bigint generated by default as identity primary key,
  escopo text not null,
  identidade_hash text not null,
  evento_hash text not null,
  criado_em timestamptz not null default now(),
  expira_em timestamptz not null,
  constraint checkout_rate_limits_escopo_check
    check (
      escopo in (
        'checkout_ip_5m',
        'checkout_ip_1h',
        'checkout_email_30m',
        'checkout_user_30m',
        'pix_ip_30m',
        'pix_email_45m'
      )
    ),
  constraint checkout_rate_limits_identidade_hash_check
    check (identidade_hash ~ '^[0-9a-f]{64}$'),
  constraint checkout_rate_limits_evento_hash_check
    check (evento_hash ~ '^[0-9a-f]{64}$'),
  constraint checkout_rate_limits_expiracao_check
    check (expira_em > criado_em),
  constraint checkout_rate_limits_evento_unique
    unique (escopo, identidade_hash, evento_hash)
);

create index if not exists checkout_rate_limits_consulta_idx
  on public.checkout_rate_limits (escopo, identidade_hash, expira_em);

create index if not exists checkout_rate_limits_expiracao_idx
  on public.checkout_rate_limits (expira_em);

alter table public.checkout_rate_limits enable row level security;

revoke all privileges on table public.checkout_rate_limits
  from public, anon, authenticated, service_role;

revoke all privileges on sequence public.checkout_rate_limits_id_seq
  from public, anon, authenticated, service_role;

create or replace function public.consumir_rate_limit_checkout(
  p_escopo text,
  p_identidade_hash text,
  p_evento_hash text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_agora timestamptz := clock_timestamp();
  v_limite integer;
  v_janela_segundos integer;
  v_quantidade integer;
  v_primeira_expiracao timestamptz;
  v_retry_after integer;
begin
  case p_escopo
    when 'checkout_ip_5m' then
      v_limite := 10;
      v_janela_segundos := 300;
    when 'checkout_ip_1h' then
      v_limite := 40;
      v_janela_segundos := 3600;
    when 'checkout_email_30m' then
      v_limite := 6;
      v_janela_segundos := 1800;
    when 'checkout_user_30m' then
      v_limite := 8;
      v_janela_segundos := 1800;
    when 'pix_ip_30m' then
      v_limite := 8;
      v_janela_segundos := 1800;
    when 'pix_email_45m' then
      v_limite := 2;
      v_janela_segundos := 2700;
    else
      raise exception 'Escopo de rate limit invalido'
        using errcode = '22023';
  end case;

  if p_identidade_hash is null
    or p_identidade_hash !~ '^[0-9a-f]{64}$'
    or p_evento_hash is null
    or p_evento_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Identificador de rate limit invalido'
      using errcode = '22023';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_escopo || ':' || p_identidade_hash,
      0
    )
  );

  delete from public.checkout_rate_limits
  where escopo = p_escopo
    and identidade_hash = p_identidade_hash
    and expira_em <= v_agora;

  if exists (
    select 1
    from public.checkout_rate_limits
    where escopo = p_escopo
      and identidade_hash = p_identidade_hash
      and evento_hash = p_evento_hash
      and expira_em > v_agora
  ) then
    return jsonb_build_object(
      'permitido', true,
      'retry_after', 0
    );
  end if;

  select count(*), min(expira_em)
  into v_quantidade, v_primeira_expiracao
  from public.checkout_rate_limits
  where escopo = p_escopo
    and identidade_hash = p_identidade_hash
    and expira_em > v_agora;

  if v_quantidade >= v_limite then
    v_retry_after := greatest(
      1,
      ceil(
        extract(epoch from (v_primeira_expiracao - v_agora))
      )::integer
    );

    return jsonb_build_object(
      'permitido', false,
      'retry_after', v_retry_after
    );
  end if;

  insert into public.checkout_rate_limits (
    escopo,
    identidade_hash,
    evento_hash,
    criado_em,
    expira_em
  )
  values (
    p_escopo,
    p_identidade_hash,
    p_evento_hash,
    v_agora,
    v_agora + pg_catalog.make_interval(secs => v_janela_segundos)
  );

  return jsonb_build_object(
    'permitido', true,
    'retry_after', 0
  );
end;
$function$;

revoke all privileges on function public.consumir_rate_limit_checkout(
  text,
  text,
  text
) from public, anon, authenticated, service_role;

grant execute on function public.consumir_rate_limit_checkout(
  text,
  text,
  text
) to service_role;

commit;
