begin;

-- ============================================================
-- 1. TABELAS DO MÓDULO REVENDAS / CONSIGNAÇÃO
-- ============================================================

create table if not exists public.revendedoras (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text,
  whatsapp text,
  email text,
  cpf_cnpj text,
  cidade text,
  estado text,
  endereco text,
  comissao_padrao numeric(5,2) not null default 20.00 check (comissao_padrao >= 0 and comissao_padrao <= 100),
  periodicidade_acerto_dias integer not null default 15 check (periodicidade_acerto_dias > 0),
  data_inicio date not null default current_date,
  observacoes text,
  status text not null default 'Ativa' check (status in ('Ativa', 'Pausada', 'Encerrada')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.revenda_remessas (
  id bigint generated by default as identity primary key,
  numero text not null unique,
  revendedora_id bigint not null references public.revendedoras(id) on delete restrict,
  data_envio timestamptz not null default now(),
  comissao_padrao_remessa numeric(5,2) not null default 20.00 check (comissao_padrao_remessa >= 0 and comissao_padrao_remessa <= 100),
  status text not null default 'Enviada' check (
    status in (
      'Em preparação',
      'Enviada',
      'Parcialmente vendida',
      'Aguardando acerto',
      'Parcialmente acertada',
      'Acertada',
      'Parcialmente devolvida',
      'Encerrada'
    )
  ),
  observacao text,
  responsavel text,
  total_pecas_enviadas integer not null default 0 check (total_pecas_enviadas >= 0),
  total_valor_enviado numeric(12,2) not null default 0 check (total_valor_enviado >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.revenda_remessa_itens (
  id bigint generated by default as identity primary key,
  remessa_id bigint not null references public.revenda_remessas(id) on delete cascade,
  produto_id bigint not null references public.produtos(id),
  produto_tamanho_id bigint references public.produto_tamanhos(id),
  produto_nome text not null,
  sku text,
  tamanho text,
  quantidade_enviada integer not null check (quantidade_enviada > 0),
  quantidade_vendida integer not null default 0 check (quantidade_vendida >= 0 and quantidade_vendida <= quantidade_enviada),
  quantidade_devolvida integer not null default 0 check (quantidade_devolvida >= 0 and (quantidade_vendida + quantidade_devolvida) <= quantidade_enviada),
  preco_venda_sugerido numeric(10,2) not null check (preco_venda_sugerido >= 0),
  custo_unitario numeric(10,2) not null default 0,
  comissao_percentual numeric(5,2) not null check (comissao_percentual >= 0 and comissao_percentual <= 100),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.revenda_vendas (
  id bigint generated by default as identity primary key,
  remessa_item_id bigint not null references public.revenda_remessa_itens(id) on delete restrict,
  remessa_id bigint not null references public.revenda_remessas(id) on delete restrict,
  revendedora_id bigint not null references public.revendedoras(id) on delete restrict,
  produto_id bigint not null references public.produtos(id),
  produto_tamanho_id bigint references public.produto_tamanhos(id),
  produto_nome text not null,
  tamanho text,
  quantidade integer not null check (quantidade > 0),
  preco_unitario_vendido numeric(10,2) not null check (preco_unitario_vendido >= 0),
  valor_total_bruto numeric(10,2) not null check (valor_total_bruto >= 0),
  comissao_percentual numeric(5,2) not null check (comissao_percentual >= 0 and comissao_percentual <= 100),
  valor_comissao numeric(10,2) not null check (valor_comissao >= 0),
  valor_loja numeric(10,2) not null check (valor_loja >= 0),
  data_venda timestamptz not null default now(),
  observacao text,
  criado_em timestamptz not null default now()
);

create table if not exists public.revenda_devolucoes (
  id bigint generated by default as identity primary key,
  remessa_item_id bigint not null references public.revenda_remessa_itens(id) on delete restrict,
  remessa_id bigint not null references public.revenda_remessas(id) on delete restrict,
  revendedora_id bigint not null references public.revendedoras(id) on delete restrict,
  produto_id bigint not null references public.produtos(id),
  produto_tamanho_id bigint references public.produto_tamanhos(id),
  quantidade integer not null check (quantidade > 0),
  motivo text,
  data_devolucao timestamptz not null default now(),
  criado_em timestamptz not null default now()
);

create table if not exists public.revenda_acertos (
  id bigint generated by default as identity primary key,
  revendedora_id bigint not null references public.revendedoras(id) on delete restrict,
  periodo_inicio date not null,
  periodo_fim date not null,
  data_vencimento date not null,
  total_vendido_bruto numeric(10,2) not null default 0,
  total_comissao numeric(10,2) not null default 0,
  total_devido_loja numeric(10,2) not null default 0,
  total_pago numeric(10,2) not null default 0,
  saldo_pendente numeric(10,2) not null default 0,
  status text not null default 'Aguardando' check (status in ('Aguardando', 'Parcial', 'Pago', 'Atrasado')),
  observacao text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.revenda_pagamentos (
  id bigint generated by default as identity primary key,
  revendedora_id bigint not null references public.revendedoras(id) on delete restrict,
  acerto_id bigint references public.revenda_acertos(id) on delete set null,
  valor numeric(10,2) not null check (valor > 0),
  forma_pagamento text not null check (forma_pagamento in ('Pix', 'Transferência', 'Dinheiro', 'Cartão', 'Outro')),
  data_pagamento timestamptz not null default now(),
  comprovante_ref text,
  observacao text,
  criado_em timestamptz not null default now()
);

-- ============================================================
-- 2. SEQUÊNCIAS & ÍNDICES
-- ============================================================

create sequence if not exists public.revenda_remessa_numero_seq start 1;

create index if not exists revenda_remessas_revendedora_idx on public.revenda_remessas (revendedora_id);
create index if not exists revenda_remessa_itens_remessa_idx on public.revenda_remessa_itens (remessa_id);
create index if not exists revenda_remessa_itens_produto_idx on public.revenda_remessa_itens (produto_id);
create index if not exists revenda_vendas_revendedora_idx on public.revenda_vendas (revendedora_id, data_venda desc);
create index if not exists revenda_acertos_revendedora_idx on public.revenda_acertos (revendedora_id, data_vencimento desc);
create index if not exists revenda_pagamentos_revendedora_idx on public.revenda_pagamentos (revendedora_id, data_pagamento desc);

-- ============================================================
-- 3. ROW LEVEL SECURITY (PROTEÇÃO TOTAL ADMIN)
-- ============================================================

alter table public.revendedoras enable row level security;
alter table public.revenda_remessas enable row level security;
alter table public.revenda_remessa_itens enable row level security;
alter table public.revenda_vendas enable row level security;
alter table public.revenda_devolucoes enable row level security;
alter table public.revenda_acertos enable row level security;
alter table public.revenda_pagamentos enable row level security;

create policy revendedoras_admin_all on public.revendedoras
  for all to authenticated
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

create policy revenda_remessas_admin_all on public.revenda_remessas
  for all to authenticated
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

create policy revenda_remessa_itens_admin_all on public.revenda_remessa_itens
  for all to authenticated
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

create policy revenda_vendas_admin_all on public.revenda_vendas
  for all to authenticated
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

create policy revenda_devolucoes_admin_all on public.revenda_devolucoes
  for all to authenticated
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

create policy revenda_acertos_admin_all on public.revenda_acertos
  for all to authenticated
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

create policy revenda_pagamentos_admin_all on public.revenda_pagamentos
  for all to authenticated
  using (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin')
  with check (auth.jwt() -> 'app_metadata' ->> 'role' = 'admin');

-- ============================================================
-- 4. RPCS TRANSACIONAIS E ATÔMICAS
-- ============================================================

-- RPC: CRIAR REMESSA COM BAIXA ATÔMICA DE ESTOQUE LOJA
create or replace function public.criar_remessa_consignacao(
  p_revendedora_id bigint,
  p_itens jsonb,
  p_observacao text default null,
  p_responsavel text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_revendedora public.revendedoras%rowtype;
  v_remessa_id bigint;
  v_numero_seq bigint;
  v_numero text;
  v_item jsonb;
  v_produto_id bigint;
  v_tamanho_id bigint;
  v_tamanho text;
  v_quantidade integer;
  v_preco numeric(10,2);
  v_custo numeric(10,2);
  v_comissao numeric(5,2);
  v_produto_nome text;
  v_sku text;
  v_estoque_atual integer;
  v_tamanho_estoque integer;
  v_total_pecas integer := 0;
  v_total_valor numeric(12,2) := 0;
begin
  if auth.jwt() -> 'app_metadata' ->> 'role' <> 'admin' then
    raise exception 'Acesso restrito ao administrador' using errcode = '42501';
  end if;

  select * into v_revendedora from public.revendedoras where id = p_revendedora_id;
  if not found then
    raise exception 'Revendedora não encontrada' using errcode = 'P0002';
  end if;

  if p_itens is null or jsonb_array_length(p_itens) = 0 then
    raise exception 'A remessa precisa conter ao menos um item' using errcode = '22023';
  end if;

  v_numero_seq := nextval('public.revenda_remessa_numero_seq');
  v_numero := 'REM-' || lpad(v_numero_seq::text, 6, '0');

  insert into public.revenda_remessas (
    numero,
    revendedora_id,
    data_envio,
    comissao_padrao_remessa,
    status,
    observacao,
    responsavel,
    total_pecas_enviadas,
    total_valor_enviado
  ) values (
    v_numero,
    p_revendedora_id,
    now(),
    v_revendedora.comissao_padrao,
    'Enviada',
    p_observacao,
    p_responsavel,
    0,
    0
  ) returning id into v_remessa_id;

  for v_item in select * from jsonb_array_elements(p_itens)
  loop
    v_produto_id := (v_item->>'produto_id')::bigint;
    v_tamanho_id := nullif(v_item->>'produto_tamanho_id', '')::bigint;
    v_tamanho := nullif(btrim(v_item->>'tamanho'), '');
    v_quantidade := coalesce((v_item->>'quantidade')::integer, 0);
    v_preco := coalesce((v_item->>'preco_venda_sugerido')::numeric, 0);
    v_comissao := coalesce((v_item->>'comissao_percentual')::numeric, v_revendedora.comissao_padrao);

    if v_quantidade <= 0 then
      raise exception 'Quantidade inválida para o produto %', v_produto_id using errcode = '22023';
    end if;

    -- Trava produto e valida estoque loja
    select nome, sku, quantidade, custo into v_produto_nome, v_sku, v_estoque_atual, v_custo
    from public.produtos
    where id = v_produto_id
    for update;

    if not found then
      raise exception 'Produto % não encontrado', v_produto_id using errcode = 'P0002';
    end if;

    if v_estoque_atual < v_quantidade then
      raise exception 'Estoque insuficiente na loja para o produto % (Disponível: %, Solicitado: %)',
        v_produto_nome, v_estoque_atual, v_quantidade using errcode = 'P0001';
    end if;

    -- Valida tamanho se aplicável
    if v_tamanho_id is not null then
      select quantidade into v_tamanho_estoque
      from public.produto_tamanhos
      where id = v_tamanho_id
      for update;

      if not found or v_tamanho_estoque < v_quantidade then
        raise exception 'Estoque insuficiente para tamanho % do produto % (Disponível: %, Solicitado: %)',
          v_tamanho, v_produto_nome, coalesce(v_tamanho_estoque, 0), v_quantidade using errcode = 'P0001';
      end if;

      update public.produto_tamanhos
      set quantidade = quantidade - v_quantidade
      where id = v_tamanho_id;
    end if;

    -- Baixa estoque loja
    update public.produtos
    set quantidade = quantidade - v_quantidade
    where id = v_produto_id;

    -- Insere item da remessa
    insert into public.revenda_remessa_itens (
      remessa_id,
      produto_id,
      produto_tamanho_id,
      produto_nome,
      sku,
      tamanho,
      quantidade_enviada,
      preco_venda_sugerido,
      custo_unitario,
      comissao_percentual
    ) values (
      v_remessa_id,
      v_produto_id,
      v_tamanho_id,
      v_produto_nome,
      v_sku,
      v_tamanho,
      v_quantidade,
      v_preco,
      coalesce(v_custo, 0),
      v_comissao
    );

    -- Movimentação auditável
    insert into public.movimentacoes (
      produto_id,
      produto_nome,
      tipo,
      quantidade,
      estoque_anterior,
      estoque_atual,
      observacao,
      data
    ) values (
      v_produto_id,
      v_produto_nome || coalesce(' (' || v_tamanho || ')', ''),
      'saida',
      v_quantidade,
      v_estoque_atual,
      v_estoque_atual - v_quantidade,
      'Envio em consignação: ' || v_numero || ' para ' || v_revendedora.nome,
      now()
    );

    v_total_pecas := v_total_pecas + v_quantidade;
    v_total_valor := v_total_valor + (v_quantidade * v_preco);
  end loop;

  update public.revenda_remessas
  set total_pecas_enviadas = v_total_pecas,
      total_valor_enviado = v_total_valor
  where id = v_remessa_id;

  return jsonb_build_object(
    'sucesso', true,
    'remessa_id', v_remessa_id,
    'numero', v_numero,
    'total_pecas', v_total_pecas,
    'total_valor', v_total_valor
  );
end;
$function$;

-- RPC: REGISTRAR VENDA CONSIGNADA COM CONGELAMENTO DE COMISSÃO
create or replace function public.registrar_venda_consignada(
  p_remessa_item_id bigint,
  p_quantidade integer,
  p_preco_unitario numeric,
  p_data_venda timestamptz default now(),
  p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_item public.revenda_remessa_itens%rowtype;
  v_remessa public.revenda_remessas%rowtype;
  v_revendedora public.revendedoras%rowtype;
  v_saldo_consignado integer;
  v_valor_bruto numeric(10,2);
  v_valor_comissao numeric(10,2);
  v_valor_loja numeric(10,2);
  v_venda_id bigint;
  v_total_enviado integer;
  v_total_vendido integer;
  v_total_devolvido integer;
  v_novo_status text;
begin
  if auth.jwt() -> 'app_metadata' ->> 'role' <> 'admin' then
    raise exception 'Acesso restrito ao administrador' using errcode = '42501';
  end if;

  if p_quantidade <= 0 or p_preco_unitario < 0 then
    raise exception 'Quantidade ou preço de venda inválidos' using errcode = '22023';
  end if;

  select * into v_item from public.revenda_remessa_itens where id = p_remessa_item_id for update;
  if not found then
    raise exception 'Item da remessa não encontrado' using errcode = 'P0002';
  end if;

  select * into v_remessa from public.revenda_remessas where id = v_item.remessa_id;
  select * into v_revendedora from public.revendedoras where id = v_remessa.revendedora_id;

  v_saldo_consignado := v_item.quantidade_enviada - v_item.quantidade_vendida - v_item.quantidade_devolvida;
  if v_saldo_consignado < p_quantidade then
    raise exception 'Quantidade informada (%) maior que o saldo consignado disponível (%)',
      p_quantidade, v_saldo_consignado using errcode = 'P0001';
  end if;

  v_valor_bruto := p_quantidade * p_preco_unitario;
  v_valor_comissao := round(v_valor_bruto * (v_item.comissao_percentual / 100.0), 2);
  v_valor_loja := v_valor_bruto - v_valor_comissao;

  update public.revenda_remessa_itens
  set quantidade_vendida = quantidade_vendida + p_quantidade,
      atualizado_em = now()
  where id = p_remessa_item_id;

  insert into public.revenda_vendas (
    remessa_item_id,
    remessa_id,
    revendedora_id,
    produto_id,
    produto_tamanho_id,
    produto_nome,
    tamanho,
    quantidade,
    preco_unitario_vendido,
    valor_total_bruto,
    comissao_percentual,
    valor_comissao,
    valor_loja,
    data_venda,
    observacao
  ) values (
    p_remessa_item_id,
    v_item.remessa_id,
    v_remessa.revendedora_id,
    v_item.produto_id,
    v_item.produto_tamanho_id,
    v_item.produto_nome,
    v_item.tamanho,
    p_quantidade,
    p_preco_unitario,
    v_valor_bruto,
    v_item.comissao_percentual,
    v_valor_comissao,
    v_valor_loja,
    coalesce(p_data_venda, now()),
    p_observacao
  ) returning id into v_venda_id;

  -- Atualiza status da remessa
  select sum(quantidade_enviada), sum(quantidade_vendida), sum(quantidade_devolvida)
  into v_total_enviado, v_total_vendido, v_total_devolvido
  from public.revenda_remessa_itens
  where remessa_id = v_item.remessa_id;

  if (v_total_vendido + v_total_devolvido) >= v_total_enviado then
    v_novo_status := 'Acertada';
  else
    v_novo_status := 'Parcialmente vendida';
  end if;

  update public.revenda_remessas
  set status = v_novo_status,
      atualizado_em = now()
  where id = v_item.remessa_id;

  return jsonb_build_object(
    'sucesso', true,
    'venda_id', v_venda_id,
    'quantidade', p_quantidade,
    'valor_bruto', v_valor_bruto,
    'comissao', v_valor_comissao,
    'valor_loja', v_valor_loja
  );
end;
$function$;

-- RPC: REGISTRAR DEVOLUÇÃO COM RETORNO AO ESTOQUE LOJA
create or replace function public.registrar_devolucao_consignada(
  p_remessa_item_id bigint,
  p_quantidade integer,
  p_motivo text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_item public.revenda_remessa_itens%rowtype;
  v_remessa public.revenda_remessas%rowtype;
  v_revendedora public.revendedoras%rowtype;
  v_saldo_consignado integer;
  v_devolucao_id bigint;
  v_estoque_anterior integer;
  v_total_enviado integer;
  v_total_vendido integer;
  v_total_devolvido integer;
  v_novo_status text;
begin
  if auth.jwt() -> 'app_metadata' ->> 'role' <> 'admin' then
    raise exception 'Acesso restrito ao administrador' using errcode = '42501';
  end if;

  if p_quantidade <= 0 then
    raise exception 'Quantidade de devolução inválida' using errcode = '22023';
  end if;

  select * into v_item from public.revenda_remessa_itens where id = p_remessa_item_id for update;
  if not found then
    raise exception 'Item da remessa não encontrado' using errcode = 'P0002';
  end if;

  select * into v_remessa from public.revenda_remessas where id = v_item.remessa_id;
  select * into v_revendedora from public.revendedoras where id = v_remessa.revendedora_id;

  v_saldo_consignado := v_item.quantidade_enviada - v_item.quantidade_vendida - v_item.quantidade_devolvida;
  if v_saldo_consignado < p_quantidade then
    raise exception 'Quantidade de devolução (%) maior que o saldo consignado (%)',
      p_quantidade, v_saldo_consignado using errcode = 'P0001';
  end if;

  -- Atualiza remessa_item
  update public.revenda_remessa_itens
  set quantidade_devolvida = quantidade_devolvida + p_quantidade,
      atualizado_em = now()
  where id = p_remessa_item_id;

  -- Devolve para o produto e tamanho
  select quantidade into v_estoque_anterior
  from public.produtos
  where id = v_item.produto_id
  for update;

  update public.produtos
  set quantidade = quantidade + p_quantidade
  where id = v_item.produto_id;

  if v_item.produto_tamanho_id is not null then
    update public.produto_tamanhos
    set quantidade = quantidade + p_quantidade
    where id = v_item.produto_tamanho_id;
  end if;

  insert into public.revenda_devolucoes (
    remessa_item_id,
    remessa_id,
    revendedora_id,
    produto_id,
    produto_tamanho_id,
    quantidade,
    motivo,
    data_devolucao
  ) values (
    p_remessa_item_id,
    v_item.remessa_id,
    v_remessa.revendedora_id,
    v_item.produto_id,
    v_item.produto_tamanho_id,
    p_quantidade,
    p_motivo,
    now()
  ) returning id into v_devolucao_id;

  -- Movimentação auditável
  insert into public.movimentacoes (
    produto_id,
    produto_nome,
    tipo,
    quantidade,
    estoque_anterior,
    estoque_atual,
    observacao,
    data
  ) values (
    v_item.produto_id,
    v_item.produto_nome || coalesce(' (' || v_item.tamanho || ')', ''),
    'entrada',
    p_quantidade,
    v_estoque_anterior,
    v_estoque_anterior + p_quantidade,
    'Devolução de consignação da remessa ' || v_remessa.numero || ' de ' || v_revendedora.nome || coalesce(' - Motivo: ' || p_motivo, ''),
    now()
  );

  -- Atualiza status da remessa
  select sum(quantidade_enviada), sum(quantidade_vendida), sum(quantidade_devolvida)
  into v_total_enviado, v_total_vendido, v_total_devolvido
  from public.revenda_remessa_itens
  where remessa_id = v_item.remessa_id;

  if (v_total_vendido + v_total_devolvido) >= v_total_enviado then
    v_novo_status := 'Encerrada';
  else
    v_novo_status := 'Parcialmente devolvida';
  end if;

  update public.revenda_remessas
  set status = v_novo_status,
      atualizado_em = now()
  where id = v_item.remessa_id;

  return jsonb_build_object(
    'sucesso', true,
    'devolucao_id', v_devolucao_id,
    'quantidade', p_quantidade,
    'estoque_loja_atual', v_estoque_anterior + p_quantidade
  );
end;
$function$;

-- RPC: REGISTRAR PAGAMENTO DE ACERTO
create or replace function public.registrar_pagamento_acerto(
  p_revendedora_id bigint,
  p_valor numeric,
  p_forma_pagamento text,
  p_acerto_id bigint default null,
  p_data_pagamento timestamptz default now(),
  p_observacao text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_pagamento_id bigint;
  v_acerto public.revenda_acertos%rowtype;
  v_novo_pago numeric(10,2);
  v_novo_saldo numeric(10,2);
  v_novo_status text;
begin
  if auth.jwt() -> 'app_metadata' ->> 'role' <> 'admin' then
    raise exception 'Acesso restrito ao administrador' using errcode = '42501';
  end if;

  if p_valor <= 0 then
    raise exception 'Valor de pagamento deve ser maior que zero' using errcode = '22023';
  end if;

  if p_forma_pagamento not in ('Pix', 'Transferência', 'Dinheiro', 'Cartão', 'Outro') then
    raise exception 'Forma de pagamento inválida' using errcode = '22023';
  end if;

  insert into public.revenda_pagamentos (
    revendedora_id,
    acerto_id,
    valor,
    forma_pagamento,
    data_pagamento,
    observacao
  ) values (
    p_revendedora_id,
    p_acerto_id,
    p_valor,
    p_forma_pagamento,
    coalesce(p_data_pagamento, now()),
    p_observacao
  ) returning id into v_pagamento_id;

  if p_acerto_id is not null then
    select * into v_acerto from public.revenda_acertos where id = p_acerto_id for update;
    if found then
      v_novo_pago := v_acerto.total_pago + p_valor;
      v_novo_saldo := greatest(0, v_acerto.total_devido_loja - v_novo_pago);
      if v_novo_saldo = 0 then
        v_novo_status := 'Pago';
      else
        v_novo_status := 'Parcial';
      end if;

      update public.revenda_acertos
      set total_pago = v_novo_pago,
          saldo_pendente = v_novo_saldo,
          status = v_novo_status,
          atualizado_em = now()
      where id = p_acerto_id;
    end if;
  end if;

  return jsonb_build_object(
    'sucesso', true,
    'pagamento_id', v_pagamento_id,
    'valor', p_valor
  );
end;
$function$;

-- Privilégios de execução
revoke all privileges on function public.criar_remessa_consignacao(bigint, jsonb, text, text) from public, anon, authenticated, service_role;
revoke all privileges on function public.registrar_venda_consignada(bigint, integer, numeric, timestamptz, text) from public, anon, authenticated, service_role;
revoke all privileges on function public.registrar_devolucao_consignada(bigint, integer, text) from public, anon, authenticated, service_role;
revoke all privileges on function public.registrar_pagamento_acerto(bigint, numeric, text, bigint, timestamptz, text) from public, anon, authenticated, service_role;

grant execute on function public.criar_remessa_consignacao(bigint, jsonb, text, text) to authenticated, service_role;
grant execute on function public.registrar_venda_consignada(bigint, integer, numeric, timestamptz, text) to authenticated, service_role;
grant execute on function public.registrar_devolucao_consignada(bigint, integer, text) to authenticated, service_role;
grant execute on function public.registrar_pagamento_acerto(bigint, numeric, text, bigint, timestamptz, text) to authenticated, service_role;

grant usage, select on sequence public.revenda_remessa_numero_seq to authenticated, service_role;

commit;
