begin;

-- Esta migration prepara pagamentos Mercado Pago sem alterar pedidos antigos.
-- O QR Code Pix e o código copia-e-cola não são persistidos.

alter table public.pedidos
  add column if not exists forma_pagamento text,
  add column if not exists status_pagamento text,
  add column if not exists pagamento_provider text,
  add column if not exists pagamento_id text,
  add column if not exists pagamento_external_reference text,
  add column if not exists pagamento_idempotency_key uuid,
  add column if not exists pagamento_status_detail text,
  add column if not exists pagamento_atualizado_em timestamptz,
  add column if not exists pix_expiracao timestamptz,
  add column if not exists pagamento_consulta_token uuid,
  add column if not exists reserva_status text,
  add column if not exists reserva_expira_em timestamptz;

create unique index if not exists pedidos_pagamento_id_unique_idx
  on public.pedidos (pagamento_id)
  where pagamento_id is not null;

create unique index if not exists pedidos_pagamento_external_reference_unique_idx
  on public.pedidos (pagamento_external_reference)
  where pagamento_external_reference is not null;

create unique index if not exists pedidos_pagamento_idempotency_unique_idx
  on public.pedidos (pagamento_idempotency_key)
  where pagamento_idempotency_key is not null;

create unique index if not exists pedidos_pagamento_consulta_token_unique_idx
  on public.pedidos (pagamento_consulta_token)
  where pagamento_consulta_token is not null;

create index if not exists pedidos_reserva_expiracao_idx
  on public.pedidos (reserva_expira_em)
  where reserva_status = 'reservado';

do $migration$
begin
  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conname = 'pedidos_forma_pagamento_check'
      and conrelid = 'public.pedidos'::regclass
  ) then
    alter table public.pedidos
      add constraint pedidos_forma_pagamento_check
      check (
        forma_pagamento is null
        or forma_pagamento in ('Pix', 'Cartão de crédito')
      ) not valid;
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conname = 'pedidos_status_pagamento_check'
      and conrelid = 'public.pedidos'::regclass
  ) then
    alter table public.pedidos
      add constraint pedidos_status_pagamento_check
      check (
        status_pagamento is null
        or status_pagamento in (
          'pendente',
          'aprovado',
          'recusado',
          'cancelado',
          'expirado',
          'reembolsado'
        )
      ) not valid;
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint
    where conname = 'pedidos_reserva_status_check'
      and conrelid = 'public.pedidos'::regclass
  ) then
    alter table public.pedidos
      add constraint pedidos_reserva_status_check
      check (
        reserva_status is null
        or reserva_status in ('reservado', 'confirmado', 'liberado')
      ) not valid;
  end if;
end;
$migration$;

alter table public.pedidos
  validate constraint pedidos_forma_pagamento_check;
alter table public.pedidos
  validate constraint pedidos_status_pagamento_check;
alter table public.pedidos
  validate constraint pedidos_reserva_status_check;

create table if not exists public.reservas_estoque (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null
    references public.pedidos(id) on delete cascade,
  pedido_item_id bigint not null
    references public.pedido_itens(id) on delete cascade,
  produto_id bigint not null
    references public.produtos(id),
  produto_tamanho_id bigint
    references public.produto_tamanhos(id),
  tamanho text,
  quantidade integer not null,
  status text not null default 'reservado',
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reservas_estoque_pedido_item_unique unique (pedido_item_id),
  constraint reservas_estoque_quantidade_check check (quantidade > 0),
  constraint reservas_estoque_status_check
    check (status in ('reservado', 'confirmado', 'liberado'))
);

create index if not exists reservas_estoque_pedido_idx
  on public.reservas_estoque (pedido_id);

create index if not exists reservas_estoque_expiracao_idx
  on public.reservas_estoque (expires_at)
  where status = 'reservado';

create or replace function public.liberar_reserva_pedido(
  p_pedido_id bigint,
  p_motivo text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_reserva record;
  v_estoque_anterior integer;
  v_produto_nome text;
  v_liberou boolean := false;
begin
  for v_reserva in
    select *
    from public.reservas_estoque
    where pedido_id = p_pedido_id
      and status = 'reservado'
    order by produto_id, produto_tamanho_id nulls first, id
    for update
  loop
    select quantidade, nome
    into v_estoque_anterior, v_produto_nome
    from public.produtos
    where id = v_reserva.produto_id
    for update;

    if not found then
      raise exception 'Produto % da reserva não encontrado', v_reserva.produto_id
        using errcode = 'P0001';
    end if;

    update public.produtos
    set quantidade = quantidade + v_reserva.quantidade
    where id = v_reserva.produto_id;

    if v_reserva.produto_tamanho_id is not null then
      perform 1
      from public.produto_tamanhos
      where id = v_reserva.produto_tamanho_id
        and produto_id = v_reserva.produto_id
      for update;

      if not found then
        raise exception 'Tamanho da reserva % não encontrado', v_reserva.id
          using errcode = 'P0001';
      end if;

      update public.produto_tamanhos
      set quantidade = quantidade + v_reserva.quantidade
      where id = v_reserva.produto_tamanho_id;
    end if;

    insert into public.movimentacoes (
      produto_id,
      produto_nome,
      tipo,
      quantidade,
      estoque_anterior,
      estoque_atual,
      observacao,
      data
    ) values (
      v_reserva.produto_id,
      v_produto_nome,
      'entrada',
      v_reserva.quantidade,
      v_estoque_anterior,
      v_estoque_anterior + v_reserva.quantidade,
      format(
        'Liberação de reserva do pedido %s: %s',
        p_pedido_id,
        left(coalesce(p_motivo, 'pagamento não concluído'), 250)
      ),
      now()
    );

    update public.reservas_estoque
    set status = 'liberado',
        updated_at = now()
    where id = v_reserva.id;

    v_liberou := true;
  end loop;

  if v_liberou then
    update public.pedidos
    set reserva_status = 'liberado'
    where id = p_pedido_id
      and reserva_status = 'reservado';
  end if;

  return v_liberou;
end;
$function$;

create or replace function public.criar_pedido_pagamento(
  p_user_id uuid,
  p_email_cliente text,
  p_cliente text,
  p_itens jsonb,
  p_cupom text,
  p_idempotency_key uuid,
  p_entrega jsonb,
  p_forma_pagamento text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_pedido jsonb;
  v_pedido_id bigint;
  v_numero text;
  v_existente public.pedidos%rowtype;
  -- O Pix vence em 30 minutos no provedor. A reserva ganha margem para
  -- a notificação chegar antes de entrar na fila de reconciliação.
  v_expira_em timestamptz := now() + interval '40 minutes';
begin
  if p_forma_pagamento not in ('Pix', 'Cartão de crédito') then
    raise exception 'Forma de pagamento inválida'
      using errcode = '22023';
  end if;

  select *
  into v_existente
  from public.pedidos
  where idempotency_key = p_idempotency_key
  for update;

  if found then
    if v_existente.forma_pagamento is null
      or v_existente.forma_pagamento <> p_forma_pagamento then
      raise exception 'idempotency_key já utilizada por outro fluxo de pedido'
        using errcode = 'P0001';
    end if;

    return to_jsonb(v_existente) || jsonb_build_object(
      'itens', (
        select coalesce(jsonb_agg(to_jsonb(i) order by i.id), '[]'::jsonb)
        from public.pedido_itens i
        where i.pedido_id = v_existente.id
      )
    );
  end if;

  -- A RPC atual recalcula produtos, cupom e frete e realiza a baixa atômica.
  -- Dentro desta mesma transação, essa baixa passa a representar a reserva.
  v_pedido := public.criar_pedido_checkout(
    p_user_id,
    p_email_cliente,
    p_cliente,
    p_itens,
    p_cupom,
    p_idempotency_key,
    p_entrega
  );

  v_pedido_id := nullif(v_pedido->>'id', '')::bigint;

  if v_pedido_id is null then
    raise exception 'A RPC de checkout não retornou o id do pedido'
      using errcode = 'P0001';
  end if;

  select numero
  into v_numero
  from public.pedidos
  where id = v_pedido_id
  for update;

  update public.pedidos
  set status = 'Aguardando pagamento',
      forma_pagamento = p_forma_pagamento,
      status_pagamento = 'pendente',
      pagamento_provider = 'mercado_pago',
      pagamento_external_reference = v_numero,
      pagamento_idempotency_key = p_idempotency_key,
      pagamento_consulta_token = gen_random_uuid(),
      pagamento_atualizado_em = now(),
      reserva_status = 'reservado',
      reserva_expira_em = v_expira_em
  where id = v_pedido_id;

  insert into public.reservas_estoque (
    pedido_id,
    pedido_item_id,
    produto_id,
    produto_tamanho_id,
    tamanho,
    quantidade,
    expires_at
  )
  select
    item.pedido_id,
    item.id,
    item.produto_id,
    tamanho.id,
    item.tamanho,
    item.quantidade,
    v_expira_em
  from public.pedido_itens item
  left join public.produto_tamanhos tamanho
    on tamanho.produto_id = item.produto_id
   and tamanho.tamanho = item.tamanho
  where item.pedido_id = v_pedido_id
  on conflict (pedido_item_id) do nothing;

  select *
  into v_existente
  from public.pedidos
  where id = v_pedido_id;

  return v_pedido || to_jsonb(v_existente) || jsonb_build_object(
    'itens', (
      select coalesce(jsonb_agg(to_jsonb(i) order by i.id), '[]'::jsonb)
      from public.pedido_itens i
      where i.pedido_id = v_pedido_id
    )
  );
end;
$function$;

create or replace function public.registrar_resultado_pagamento(
  p_pedido_id bigint,
  p_pagamento_id text,
  p_external_reference text,
  p_status_provider text,
  p_status_detail text,
  p_total_provider numeric,
  p_pix_expiracao timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_pedido public.pedidos%rowtype;
  v_status_pagamento text;
  v_status_pedido text;
begin
  select *
  into v_pedido
  from public.pedidos
  where id = p_pedido_id
  for update;

  if not found then
    raise exception 'Pedido não encontrado' using errcode = 'P0001';
  end if;

  if p_external_reference is distinct from v_pedido.pagamento_external_reference then
    raise exception 'Referência externa do pagamento inválida'
      using errcode = 'P0001';
  end if;

  if round(coalesce(p_total_provider, -1), 2) <> round(v_pedido.total, 2) then
    raise exception 'Valor do pagamento diverge do pedido'
      using errcode = 'P0001';
  end if;

  case lower(coalesce(p_status_provider, ''))
    when 'approved' then
      v_status_pagamento := 'aprovado';
      v_status_pedido := 'Confirmado';
    when 'processed' then
      v_status_pagamento := 'aprovado';
      v_status_pedido := 'Confirmado';
    when 'action_required' then
      v_status_pagamento := 'pendente';
      v_status_pedido := 'Aguardando pagamento';
    when 'pending' then
      v_status_pagamento := 'pendente';
      v_status_pedido := 'Aguardando pagamento';
    when 'rejected' then
      v_status_pagamento := 'recusado';
      v_status_pedido := 'Cancelado';
    when 'failed' then
      v_status_pagamento := 'recusado';
      v_status_pedido := 'Cancelado';
    when 'canceled' then
      v_status_pagamento := 'cancelado';
      v_status_pedido := 'Cancelado';
    when 'expired' then
      v_status_pagamento := 'expirado';
      v_status_pedido := 'Cancelado';
    when 'refunded' then
      v_status_pagamento := 'reembolsado';
      v_status_pedido := 'Cancelado';
    else
      raise exception 'Status de pagamento não reconhecido: %', p_status_provider
        using errcode = '22023';
  end case;

  -- Notificações atrasadas/repetidas não podem regredir um estado final.
  if v_pedido.status_pagamento = 'aprovado'
    and v_status_pagamento <> 'reembolsado' then
    return to_jsonb(v_pedido) || jsonb_build_object(
      'itens', (
        select coalesce(jsonb_agg(to_jsonb(i) order by i.id), '[]'::jsonb)
        from public.pedido_itens i
        where i.pedido_id = p_pedido_id
      )
    );
  end if;

  if v_pedido.status_pagamento in ('recusado', 'cancelado', 'expirado')
    and v_status_pagamento = 'pendente' then
    return to_jsonb(v_pedido) || jsonb_build_object(
      'itens', (
        select coalesce(jsonb_agg(to_jsonb(i) order by i.id), '[]'::jsonb)
        from public.pedido_itens i
        where i.pedido_id = p_pedido_id
      )
    );
  end if;

  if v_status_pagamento = 'aprovado'
    and v_pedido.reserva_status = 'liberado' then
    raise exception
      'Pagamento aprovado após liberação da reserva; requer reconciliação manual'
      using errcode = 'P0001';
  end if;

  if v_status_pagamento = 'aprovado' then
    update public.reservas_estoque
    set status = 'confirmado',
        updated_at = now()
    where pedido_id = p_pedido_id
      and status = 'reservado';

    v_pedido.reserva_status := 'confirmado';
  elsif v_status_pagamento in ('recusado', 'cancelado', 'expirado') then
    perform public.liberar_reserva_pedido(
      p_pedido_id,
      format('Mercado Pago: %s (%s)', p_status_provider, p_status_detail)
    );

    v_pedido.reserva_status := 'liberado';
  end if;

  update public.pedidos
  set status = v_status_pedido,
      status_pagamento = v_status_pagamento,
      pagamento_id = coalesce(p_pagamento_id, pagamento_id),
      pagamento_status_detail = nullif(left(p_status_detail, 200), ''),
      pagamento_atualizado_em = now(),
      pix_expiracao = coalesce(p_pix_expiracao, pix_expiracao),
      reserva_status = coalesce(v_pedido.reserva_status, reserva_status)
  where id = p_pedido_id;

  return (
    select to_jsonb(p) || jsonb_build_object(
      'itens', (
        select coalesce(jsonb_agg(to_jsonb(i) order by i.id), '[]'::jsonb)
        from public.pedido_itens i
        where i.pedido_id = p.id
      )
    )
    from public.pedidos p
    where p.id = p_pedido_id
  );
end;
$function$;

create or replace function public.obter_pedido_pagamento(
  p_numero text,
  p_consulta_token uuid
)
returns jsonb
language sql
security definer
set search_path = public, pg_temp
stable
as $function$
  select to_jsonb(p) || jsonb_build_object(
    'itens', (
      select coalesce(jsonb_agg(to_jsonb(i) order by i.id), '[]'::jsonb)
      from public.pedido_itens i
      where i.pedido_id = p.id
    )
  )
  from public.pedidos p
  where p.numero = p_numero
    and p.pagamento_consulta_token = p_consulta_token;
$function$;

alter table public.reservas_estoque enable row level security;

revoke all privileges on table public.reservas_estoque
  from public, anon, authenticated, service_role;

revoke all privileges on sequence public.reservas_estoque_id_seq
  from public, anon, authenticated, service_role;

grant select, insert, update on table public.reservas_estoque
  to service_role;

grant select, update on table public.pedidos
  to service_role;

revoke all privileges on function public.liberar_reserva_pedido(bigint, text)
  from public, anon, authenticated, service_role;
revoke all privileges on function public.criar_pedido_pagamento(
  uuid, text, text, jsonb, text, uuid, jsonb, text
)
  from public, anon, authenticated, service_role;
revoke all privileges on function public.registrar_resultado_pagamento(
  bigint, text, text, text, text, numeric, timestamptz
)
  from public, anon, authenticated, service_role;
revoke all privileges on function public.obter_pedido_pagamento(text, uuid)
  from public, anon, authenticated, service_role;

grant execute on function public.criar_pedido_pagamento(
  uuid, text, text, jsonb, text, uuid, jsonb, text
)
  to service_role;
grant execute on function public.registrar_resultado_pagamento(
  bigint, text, text, text, text, numeric, timestamptz
)
  to service_role;
grant execute on function public.obter_pedido_pagamento(text, uuid)
  to service_role;
commit;
